"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  es: {
    navbar: {
      services: "Servicios",
      projects: "Proyectos",
      contact: "Contacto",
      aria_menu: "Abrir menú"
    },
    footer: {
      text: "Potenciando negocios con tecnología"
    },
    hero: {
      badge: "Disponible para proyectos",
      title_sw: "Software &",
      title_infra: "Infraestructura",
      sub_start: "Desarrollamos sistemas a la medida y blindamos tu infraestructura de red con ",
      sub_span1: "soluciones de ciberseguridad",
      sub_mid: ". Basados en ",
      sub_span2: "México",
      sub_end: ".",
      btn_projects: "Ver proyectos",
      btn_contact: "Contáctanos"
    },
    services: {
      label: "Lo que ofrecemos",
      title: "Nuestros Servicios",
      tab_software: "Desarrollo de Software",
      tab_infra: "Infraestructura y Ciberseguridad",
      desde: "desde",
      sw1_title: "Página web corporativa",
      sw1_desc: "Diseño moderno, totalmente adaptable a móviles y optimizado para Google. Ideal para posicionar tu marca en internet.",
      sw2_title: "Menú digital y catálogos",
      sw2_desc: "Muestra tus productos en línea a través de códigos QR. Tus clientes lo ven desde el celular y tú puedes actualizarlo fácilmente.",
      sw3_title: "Sistemas a la medida",
      sw3_desc: "Soluciones con bases de datos como agendas de citas, puntos de venta básicos o portales de gestión para tu negocio.",
      sw4_title: "Landing page de ventas",
      sw4_desc: "Página estructurada para vender un producto específico y generar conversiones rápidas conectadas a WhatsApp o formularios.",
      net1_title: "Diseño e Ingeniería de Redes",
      net1_desc: "Arquitectura de topologías personalizadas y planeación de esquemas de direccionamiento IP eficientes y escalables.",
      net2_title: "Implementación Multi-Vendor",
      net2_desc: "Configuración profesional de Firewalls, Switches y Access Points empresariales para un rendimiento óptimo.",
      net3_title: "Redes Inalámbricas Enterprise",
      net3_desc: "Despliegue de soluciones Wi-Fi de alta densidad con autenticación segura bajo el estándar 802.1X.",
      net4_title: "VPNs de Alta Seguridad",
      net4_desc: "Implementación de túneles Site-to-Site para interconexión de sucursales y soluciones de Acceso Remoto.",
      net5_title: "Hardening y Ciberseguridad",
      net5_desc: "Aplicación de mejores prácticas (CIS Benchmarks) para el blindaje de equipos de red y servidores.",
      net6_title: "Gestión de Identidades",
      net6_desc: "Configuración de servicios de Active Directory para el control centralizado de usuarios, permisos y recursos."
    },
    projects: {
      label: "Nuestro trabajo",
      title: "Casos de Éxito",
      btn_demo: "Ver demostración interactiva →",
      p1_title: "Sistema de reservas — Consultorio",
      p1_desc: "Plataforma para agendar citas automatizadas. El sistema envía notificaciones, guarda el historial médico y permite al doctor gestionar todo desde un panel privado.",
      p2_title: "Menú inteligente para Restaurante",
      p2_desc: "Una experiencia web súper ligera donde los comensales escanean un código QR para explorar el menú actualizado en tiempo real sin instalar aplicaciones.",
      p3_title: "Landing page — Salón de Belleza",
      p3_desc: "Página enfocada en conversiones. Atrae tráfico local, muestra galerías interactivas y facilita la reserva de servicios a través de WhatsApp de forma directa.",
      p4_title: "Implementación Wi-Fi Corporativo",
      p4_desc: "Despliegue de red inalámbrica de alta densidad para oficinas corporativas. Autenticación segura RADIUS/802.1X, segmentación de VLANs y portal cautivo para invitados.",
      p5_title: "Ciberseguridad y VPN Site-to-Site",
      p5_desc: "Interconexión segura entre sucursal matriz y almacenes mediante túneles IPsec. Hardening de firewalls perimetrales y monitoreo de amenazas en tiempo real."
    },
    skills: {
      label: "Ecosistema Tecnológico",
      title: "Tecnologías",
      tooltip_next: "Framework para web ultrarrápida",
      tooltip_react: "Interfaces de usuario interactivas",
      tooltip_js: "Lenguaje de programación web",
      tooltip_node: "Ejecución de código en servidor",
      tooltip_postgres: "Base de datos relacional robusta",
      tooltip_html_css: "Estructura y diseño web",
      tooltip_vercel: "Plataforma de despliegue en nube",
      tooltip_git: "Control de versiones de código",
      tooltip_api: "Comunicación entre sistemas",
      tooltip_responsive: "Diseño para móviles y PC",
      tooltip_seo: "Posicionamiento en Google",
      tooltip_cybersecurity: "Protección contra amenazas",
      tooltip_vpn: "Túneles seguros y perimetrales",
      tooltip_ad: "Gestión de usuarios y permisos",
      tooltip_wifi: "Wi-Fi de alta seguridad"
    },
    contact: {
      label: "Hablemos",
      title: "¿Tienes un proyecto en mente?",
      desc: "Envíanos los detalles. Nuestro equipo te responderá a la brevedad para asesorarte y ofrecerte la mejor solución tecnológica para tu negocio.",
      wa_contact: "WhatsApp — Contacto Inmediato",
      form_name: "Tu Nombre o Empresa",
      form_name_placeholder: "Ej. Juan Pérez - Negocio X",
      form_contact: "WhatsApp o Correo de contacto",
      form_contact_placeholder: "Ej. +52 55 1234 5678",
      form_message: "Cuéntanos sobre tu proyecto",
      form_message_placeholder: "Quiero mejorar mi presencia web, requiero un sistema para...",
      form_submit: "Enviar a kodra →",
      form_note: "Tus datos están seguros. Se guardará tu solicitud y se abrirá WhatsApp para agilizar la comunicación.",
      status_sending: "Enviando...",
      status_redirecting: "Redirigiendo a WhatsApp...",
      wa_text: "Hola, me contacto desde tu portafolio.\n\nNombre: {nombre}\nContacto: {contacto}\n\nProyecto: {mensaje}"
    },
    reservaModal: {
      step1_tab: "1. Control",
      step2_tab: "2. Paciente",
      step3_tab: "3. Ajustes",
      step1_badge: "🔥 Panel del Doctor",
      step1_title: "El motor de citas que ",
      step1_title_accent: "multiplica",
      step1_title_end: " tus consultas",
      step1_pain: "¿Pierdes pacientes por no contestar WhatsApp a tiempo? ¿Tu asistente pasa horas cuadrando horarios?",
      step1_benefit1: "Recupera hasta 15 horas: ",
      step1_benefit1_sub: "Adiós a las llamadas para reagendar.",
      step1_benefit2: "Control total: ",
      step1_benefit2_sub: "Revisa tu agenda en tiempo real, estés donde estés.",
      step2_badge: "📱 Fricción Cero",
      step2_title: "Tus pacientes reservan en ",
      step2_title_accent: "3 clics",
      step2_title_end: "",
      step2_pain: "La barrera número uno para conseguir pacientes nuevos es un proceso de reserva complicado.",
      step2_benefit1: "Sin descargar apps: ",
      step2_benefit1_sub: "Funciona directo desde WhatsApp, Instagram o tu web.",
      step2_benefit2: "100% Automático: ",
      step2_benefit2_sub: "El sistema da informes, muestra disponibilidad y agenda sin que intervengas.",
      step3_badge: "⚙️ A tu medida",
      step3_title: "Tu negocio, ",
      step3_title_accent: "tus reglas",
      step3_title_end: "",
      step3_pain: "No te adaptes al software. El software debe adaptarse a la realidad de tu consultorio.",
      step3_benefit1: "Tu marca: ",
      step3_benefit1_sub: "Colores, logotipos y mensajes personalizados.",
      step3_benefit2: "Flexibilidad total: ",
      step3_benefit2_sub: "Configura descansos, horas de comida y duraciones por consulta.",
      btn_implement: "Implementar en mi Consultorio Hoy",
      scarcity: "Atención personalizada: Solo implementamos 3 sistemas nuevos por mes.",
      panel_title: "Dr. Admin Panel",
      status: "● En línea",
      citas_hoy: "Citas Hoy",
      ingresos: "Ingresos Est.",
      proximos: "Próximos Pacientes",
      ana: "Ana M. (Primera vez)",
      carlos: "Carlos R. (Seguimiento)",
      lucia: "Lucía T. (Limpieza)",
      confirmado: "Confirmado",
      pendiente: "Pendiente",
      notif_title: "¡Nueva cita agendada!",
      notif_desc: "Paciente: Roberto G. para Mañana 4:00 PM",
      bot_avatar: "Bot",
      bot_name: "Asistente Virtual",
      msg_patient: "Hola, necesito agendar una cita.",
      msg_bot: "¡Hola! Claro que sí. ¿Para qué especialidad te gustaría agendar?",
      opt1: "Odontología General",
      opt2: "Ortodoncia",
      opt3: "Limpieza Dental",
      sm_header: "Configuración del Consultorio",
      brand_colors: "Colores de Marca",
      rules: "Reglas y Horarios",
      rule1: "Aceptar pagos online",
      rule2: "Enviar recordatorio 24h",
      rule3: "Trabajar Domingos"
    },
    landingModal: {
      badge: "💅 Alto Impacto Visual",
      title: "Tu negocio abierto ",
      title_accent: "24/7 en Google",
      title_end: "",
      pain: "¿Tienes muchos seguidores pero pocas reservas reales? ¿Tus clientes se pierden preguntando precios por inbox?",
      explanation: "Tener solo Facebook no es suficiente. Una Landing Page captura a las personas que ya están buscando tus servicios en tu ciudad y los convierte en citas.",
      benefit1_title: "Atrae tráfico local: ",
      benefit1_desc: "Aparece cuando alguien busque 'salón de belleza cerca de mí'.",
      benefit2_title: "Cero dudas, más acción: ",
      benefit2_desc: "Muestra tus servicios, precios y testimonios para derribar objeciones.",
      benefit3_title: "Directo a WhatsApp: ",
      benefit3_desc: "Un flujo diseñado para que la visita termine en tu bandeja de entrada agendando.",
      btn: "Quiero mi Landing Page",
      scarcity: "🎁 Bono de Acción Rápida: Logotipo Básico y alta en Google Mi Negocio GRATIS si iniciamos hoy.",
      wa_message: "Hola, me interesa crear una Landing Page para mi negocio.",
      mockup_url: "🔒 bellaspa.com/reservas",
      mockup_hero_title: "Relajación y Belleza",
      mockup_hero_sub: "El santuario perfecto para desconectar y renovar tu energía.",
      mockup_hero_btn: "Agendar Cita Ahora",
      mockup_title: "Nuestros Servicios",
      m_service1_name: "Masaje Relajante",
      m_service1_desc: "60 min de aromaterapia y tejido profundo.",
      m_service2_name: "Facial Hidratante",
      m_service2_desc: "Limpieza profunda con ácido hialurónico.",
      m_service3_name: "Manicura Spa",
      m_service3_desc: "Exfoliación, hidratación y esmaltado semi."
    },
    menuModal: {
      badge: "🍔 Cero Fricción",
      title: "El menú que hace que tus clientes ",
      title_accent: "pidan más",
      title_end: "",
      pain: "¿Tus menús de papel se ensucian, se rompen y cada vez que cambias un precio tienes que volver a imprimir?",
      explanation: "Presentamos el Menú QR Definitivo. Cambia precios al instante, oculta platillos agotados con un clic y no vuelvas a gastar en imprenta.",
      benefit1_title: "Vende con los ojos: ",
      benefit1_desc: "Las fotos abren el apetito. Aumenta tu ticket promedio al mostrar fotos atractivas.",
      benefit2_title: "Actualización en tiempo real: ",
      benefit2_desc: "¿Se acabó el salmón? Ocúltalo de inmediato desde tu celular.",
      benefit3_title: "Ecológico y limpio: ",
      benefit3_desc: "Sin menús pegajosos pasando de mano en mano.",
      btn: "Digitalizar mi Menú Hoy",
      scarcity: "🎁 Oferta: Contrata esta semana y te regalamos 10 displays acrílicos de mesa con tu QR listo para escanear.",
      wa_message: "Hola, me interesa implementar el Menú Digital QR en mi restaurante.",
      mockup_tab1: "Destacados",
      mockup_tab2: "Pizzas",
      mockup_tab3: "Pastas",
      mockup_tab4: "Bebidas",
      dish1_name: "Pizza Margarita Rústica",
      dish1_desc: "Salsa pomodoro, mozzarella fresca, albahaca y aceite de oliva.",
      dish2_name: "Pasta Carbonara Originale",
      dish2_desc: "Guanciale crujiente, yema de huevo, queso pecorino y pimienta negra.",
      dish3_name: "Tiramisú Clásico",
      dish3_desc: "Capas de bizcocho bañado en café espresso, crema de mascarpone y cacao.",
      floating_cart: "🛒 Ver orden (2) - $405.00"
    },
    demoModal: {
      badge: "🖥 Plataforma Completa",
      title: "Todo lo que tu restaurante necesita, ",
      title_accent: "en un solo lugar",
      title_end: "",
      desc: "Desde el menú digital hasta la cocina y la caja — gestiona todo tu restaurante en tiempo real sin complicaciones.",
      tab_menu: "Menú",
      tab_mesas: "Mesas",
      tab_cocina: "Cocina",
      tab_caja: "Caja",
      tab_reportes: "Reportes",
      tab_cliente: "Vista Cliente",
      btn_submit: "Solicitar Demo Personalizada",
      scarcity: "🎁 Prueba gratis 14 días · Sin tarjeta de crédito",
      wa_message: "Hola, quiero ver una demo de Menukodra.",
      client_badge: "Cliente",
      new_category: "+ Nueva categoría",
      platillos: "platillos",
      add_platillo: "+ Agregar platillo",
      tacos: "Tacos",
      bebidas: "Bebidas",
      postres: "Postres",
      taco_bistec: "Taco de Bistec",
      taco_pastor: "Taco de Pastor",
      taco_pollo: "Taco de Pollo",
      agua_fresca: "Agua Fresca",
      refresco: "Refresco",
      churros: "Churros",
      tag_picante: "picante",
      tag_vegetariano: "vegetariano",
      new_table: "+ Nueva mesa",
      col_num: "Núm.",
      col_label: "Etiqueta",
      col_status: "Estado",
      col_qr: "QR",
      col_actions: "Acciones",
      table_status_active: "Activa",
      view_qr: "⊞ Ver QR",
      live: "En vivo",
      received: "Recibidas",
      preparing: "En preparación",
      accept: "⊙ Aceptar",
      mark_ready: "⊙ Marcar listo",
      churros_note: "con cajeta",
      caja_title: "Caja",
      caja_sub: "Mesas activas y cobros pendientes",
      view_bill: "▣ Ver cuenta",
      reportes_title: "Reportes",
      reportes_sub: "Ventas, platillos y ticket promedio",
      tot_sales: "Ventas totales",
      tot_tip: "Propina total",
      avg_ticket: "Ticket promedio",
      sessions_closed: "Sesiones cerradas",
      col_date: "Fecha",
      col_sessions: "Ses.",
      col_sales: "Ventas",
      col_tip: "Propina",
      col_total: "Total",
      col_graph: "Graf.",
      my_orders: "Mis pedidos",
      in_process: "En proceso",
      ready_pickup: "✓ ¡Listo para recoger!",
      preparing_status: "🔥 Preparando…",
      received_status: "⏱ Recibido",
      req_bill: "Solicitar la cuenta",
      call_waiter: "Llamar al mesero",
      steak_desc: "Bistec asado con cebolla y cilantro",
      pastor_desc: "Carne al pastor con piña y cebolla",
      pollo_desc: "Pollo a la plancha con guacamole",
      agua_desc: "De temporada, natural",
      refresco_desc: "Lata fría",
      churros_desc: "Con cajeta y crema",
      cart_view: "Ver orden"
    }
  },
  en: {
    navbar: {
      services: "Services",
      projects: "Projects",
      contact: "Contact",
      aria_menu: "Open menu"
    },
    footer: {
      text: "Powering businesses with technology"
    },
    hero: {
      badge: "Available for projects",
      title_sw: "Software &",
      title_infra: "Infrastructure",
      sub_start: "We develop custom systems and secure your network infrastructure with ",
      sub_span1: "cybersecurity solutions",
      sub_mid: ". Based in ",
      sub_span2: "Mexico",
      sub_end: ".",
      btn_projects: "View projects",
      btn_contact: "Contact us"
    },
    services: {
      label: "What we offer",
      title: "Our Services",
      tab_software: "Software Development",
      tab_infra: "Infrastructure & Cybersecurity",
      desde: "from",
      sw1_title: "Corporate Website",
      sw1_desc: "Modern design, fully mobile-responsive and SEO-optimized. Ideal for positioning your brand online.",
      sw2_title: "Digital Menu & Catalogs",
      sw2_desc: "Showcase your products online via QR codes. Your customers view it on their phones, and you can update it easily.",
      sw3_title: "Custom Systems",
      sw3_desc: "Database-driven solutions like booking calendars, basic POS systems, or management portals for your business.",
      sw4_title: "Sales Landing Page",
      sw4_desc: "Structured page to sell a specific product and drive quick conversions connected to WhatsApp or forms.",
      net1_title: "Network Design & Engineering",
      net1_desc: "Custom topology architecture and planning of efficient, scalable IP addressing schemes.",
      net2_title: "Multi-Vendor Implementation",
      net2_desc: "Professional configuration of enterprise Firewalls, Switches, and Access Points for optimal performance.",
      net3_title: "Enterprise Wireless Networks",
      net3_desc: "Deployment of high-density Wi-Fi solutions with secure 802.1X standard authentication.",
      net4_title: "High-Security VPNs",
      net4_desc: "Implementation of Site-to-Site tunnels for interconnecting branches and Remote Access solutions.",
      net5_title: "Hardening & Cybersecurity",
      net5_desc: "Application of best practices (CIS Benchmarks) for hardening network devices and servers.",
      net6_title: "Identity Management",
      net6_desc: "Configuration of Active Directory services for centralized control of users, permissions, and resources."
    },
    projects: {
      label: "Our work",
      title: "Success Stories",
      btn_demo: "View interactive demo →",
      p1_title: "Booking System — Clinic",
      p1_desc: "Platform for automated appointment scheduling. The system sends notifications, saves medical records, and allows the doctor to manage everything from a private panel.",
      p2_title: "Smart Restaurant Menu",
      p2_desc: "A super-lightweight web experience where diners scan a QR code to explore the menu updated in real-time without installing any apps.",
      p3_title: "Landing Page — Beauty Salon",
      p3_desc: "Conversion-focused page. Attracts local traffic, showcases interactive galleries, and makes booking services easy directly through WhatsApp.",
      p4_title: "Corporate Wi-Fi Deployment",
      p4_desc: "High-density wireless network deployment for offices. Secure RADIUS/802.1X authentication, VLAN segmentation, and guest captive portal.",
      p5_title: "Cybersecurity & Site-to-Site VPN",
      p5_desc: "Secure interconnection between headquarters and warehouses via IPsec tunnels. Hardening of perimeter firewalls and real-time threat monitoring."
    },
    skills: {
      label: "Technology Ecosystem",
      title: "Technologies",
      tooltip_next: "Framework for ultra-fast web",
      tooltip_react: "Interactive user interfaces",
      tooltip_js: "Web programming language",
      tooltip_node: "Server-side code execution",
      tooltip_postgres: "Robust relational database",
      tooltip_html_css: "Web structure and design",
      tooltip_vercel: "Cloud deployment platform",
      tooltip_git: "Code version control",
      tooltip_api: "System-to-system communication",
      tooltip_responsive: "Mobile and PC responsive design",
      tooltip_seo: "Google search engine positioning",
      tooltip_cybersecurity: "Threat protection",
      tooltip_vpn: "Secure perimeter tunnels",
      tooltip_ad: "User and permission management",
      tooltip_wifi: "High-security Wi-Fi"
    },
    contact: {
      label: "Let's Talk",
      title: "Have a project in mind?",
      desc: "Send us the details. Our team will respond as soon as possible to advise you and offer the best technological solution for your business.",
      wa_contact: "WhatsApp — Immediate Contact",
      form_name: "Your Name or Company",
      form_name_placeholder: "e.g. John Doe - Business X",
      form_contact: "WhatsApp or Contact Email",
      form_contact_placeholder: "e.g. +52 55 1234 5678",
      form_message: "Tell us about your project",
      form_message_placeholder: "I want to improve my web presence, I need a system for...",
      form_submit: "Send to kodra →",
      form_note: "Your data is secure. Your request will be saved and WhatsApp will open to speed up communication.",
      status_sending: "Sending...",
      status_redirecting: "Redirecting to WhatsApp...",
      wa_text: "Hello, I am contacting you from your portfolio.\n\nName: {nombre}\nContact: {contacto}\n\nProject: {mensaje}"
    },
    reservaModal: {
      step1_tab: "1. Control",
      step2_tab: "2. Patient",
      step3_tab: "3. Settings",
      step1_badge: "🔥 Doctor's Panel",
      step1_title: "The appointment engine that ",
      step1_title_accent: "multiplies",
      step1_title_end: " your consultations",
      step1_pain: "Do you lose patients because you don't answer WhatsApp in time? Does your assistant spend hours scheduling?",
      step1_benefit1: "Save up to 15 hours: ",
      step1_benefit1_sub: "Say goodbye to calls for rescheduling.",
      step1_benefit2: "Total control: ",
      step1_benefit2_sub: "Check your schedule in real-time, wherever you are.",
      step2_badge: "📱 Zero Friction",
      step2_title: "Your patients book in ",
      step2_title_accent: "3 clicks",
      step2_title_end: "",
      step2_pain: "The number one barrier to getting new patients is a complicated booking process.",
      step2_benefit1: "No apps to download: ",
      step2_benefit1_sub: "Works directly from WhatsApp, Instagram, or your website.",
      step2_benefit2: "100% Automatic: ",
      step2_benefit2_sub: "The system provides info, shows availability, and books without you intervening.",
      step3_badge: "⚙️ Custom Fit",
      step3_title: "Your business, ",
      step3_title_accent: "your rules",
      step3_title_end: "",
      step3_pain: "Don't adapt to the software. The software must adapt to the reality of your clinic.",
      step3_benefit1: "Your brand: ",
      step3_benefit1_sub: "Custom colors, logos, and messages.",
      step3_benefit2: "Total flexibility: ",
      step3_benefit2_sub: "Configure breaks, lunch hours, and session durations.",
      btn_implement: "Deploy in my Clinic Today",
      scarcity: "Personalized service: We only implement 3 new systems per month.",
      panel_title: "Dr. Admin Panel",
      status: "● Online",
      citas_hoy: "Appointments Today",
      ingresos: "Est. Revenue",
      proximos: "Upcoming Patients",
      ana: "Ana M. (First time)",
      carlos: "Carlos R. (Follow-up)",
      lucia: "Lucia T. (Cleaning)",
      confirmado: "Confirmed",
      pendiente: "Pending",
      notif_title: "New appointment booked!",
      notif_desc: "Patient: Roberto G. for Tomorrow 4:00 PM",
      bot_avatar: "Bot",
      bot_name: "Virtual Assistant",
      msg_patient: "Hello, I need to book an appointment.",
      msg_bot: "Hello! Absolutely. Which specialty would you like to book for?",
      opt1: "General Dentistry",
      opt2: "Orthodontics",
      opt3: "Dental Cleaning",
      sm_header: "Clinic Settings",
      brand_colors: "Brand Colors",
      rules: "Rules & Schedules",
      rule1: "Accept online payments",
      rule2: "Send 24h reminders",
      rule3: "Work on Sundays"
    },
    landingModal: {
      badge: "💅 High Visual Impact",
      title: "Your business open ",
      title_accent: "24/7 on Google",
      title_end: "",
      pain: "Have many followers but few real bookings? Do your clients get lost asking for prices via inbox?",
      explanation: "Just having Facebook is not enough. A Landing Page captures people who are already searching for your services in your city and converts them into appointments.",
      benefit1_title: "Attract local traffic: ",
      benefit1_desc: "Appear when someone searches for 'beauty salon near me'.",
      benefit2_title: "Zero doubts, more action: ",
      benefit2_desc: "Show your services, prices, and testimonials to remove objections.",
      benefit3_title: "Direct to WhatsApp: ",
      benefit3_desc: "A flow designed for the visit to end in your inbox with a booking.",
      btn: "I Want My Landing Page",
      scarcity: "🎁 Fast Action Bonus: Free Basic Logo and Google My Business setup if we start today.",
      wa_message: "Hello, I am interested in creating a Landing Page for my business.",
      mockup_url: "🔒 bellaspa.com/bookings",
      mockup_hero_title: "Relaxation & Beauty",
      mockup_hero_sub: "The perfect sanctuary to disconnect and renew your energy.",
      mockup_hero_btn: "Book Appointment Now",
      mockup_title: "Our Services",
      m_service1_name: "Relaxing Massage",
      m_service1_desc: "60 min of aromatherapy and deep tissue.",
      m_service2_name: "Hydrating Facial",
      m_service2_desc: "Deep cleansing with hyaluronic acid.",
      m_service3_name: "Manicure Spa",
      m_service3_desc: "Exfoliation, hydration, and semi-permanent polish."
    },
    menuModal: {
      badge: "🍔 Zero Friction",
      title: "The menu that makes your customers ",
      title_accent: "order more",
      title_end: "",
      pain: "Do your paper menus get dirty, torn, and every time you change a price you have to reprint?",
      explanation: "Introducing the Ultimate QR Menu. Change prices instantly, hide out-of-stock items with one click, and never spend on printing again.",
      benefit1_title: "Sell with your eyes: ",
      benefit1_desc: "Photos build appetite. Increase your average ticket by showing attractive photos.",
      benefit2_title: "Real-time updates: ",
      benefit2_desc: "Out of salmon? Hide it immediately from your phone.",
      benefit3_title: "Eco-friendly & clean: ",
      benefit3_desc: "No sticky menus passing from hand to hand.",
      btn: "Digitize My Menu Today",
      scarcity: "🎁 Offer: Sign up this week and we'll give you 10 acrylic table displays with your QR ready to scan.",
      wa_message: "Hello, I am interested in implementing the Digital QR Menu in my restaurant.",
      mockup_tab1: "Featured",
      mockup_tab2: "Pizzas",
      mockup_tab3: "Pastas",
      mockup_tab4: "Drinks",
      dish1_name: "Rustic Margherita Pizza",
      dish1_desc: "Pomodoro sauce, fresh mozzarella, basil, and olive oil.",
      dish2_name: "Original Carbonara Pasta",
      dish2_desc: "Crispy guanciale, egg yolk, pecorino cheese, and black pepper.",
      dish3_name: "Classic Tiramisu",
      dish3_desc: "Layers of sponge cake soaked in espresso, mascarpone cream, and cocoa.",
      floating_cart: "🛒 View order (2) - $405.00"
    },
    demoModal: {
      badge: "🖥 Complete Platform",
      title: "Everything your restaurant needs, ",
      title_accent: "in one place",
      title_end: "",
      desc: "From the digital menu to the kitchen and the cashier — manage your entire restaurant in real-time without complications.",
      tab_menu: "Menu",
      tab_mesas: "Tables",
      tab_cocina: "Kitchen",
      tab_caja: "Cashier",
      tab_reportes: "Reports",
      tab_cliente: "Client View",
      btn_submit: "Request Custom Demo",
      scarcity: "🎁 14-day free trial · No credit card required",
      wa_message: "Hello, I want to see a demo of Menukodra.",
      client_badge: "Client",
      new_category: "+ New category",
      platillos: "items",
      add_platillo: "+ Add dish",
      tacos: "Tacos",
      bebidas: "Drinks",
      postres: "Desserts",
      taco_bistec: "Steak Taco",
      taco_pastor: "Al Pastor Taco",
      taco_pollo: "Chicken Taco",
      agua_fresca: "Fresh Water",
      refresco: "Soda",
      churros: "Churros",
      tag_picante: "spicy",
      tag_vegetariano: "vegetarian",
      new_table: "+ New table",
      col_num: "No.",
      col_label: "Label",
      col_status: "Status",
      col_qr: "QR",
      col_actions: "Actions",
      table_status_active: "Active",
      view_qr: "⊞ View QR",
      live: "Live",
      received: "Received",
      preparing: "Preparing",
      accept: "⊙ Accept",
      mark_ready: "⊙ Mark ready",
      churros_note: "with caramel",
      caja_title: "Cashier",
      caja_sub: "Active tables and pending payments",
      view_bill: "▣ View bill",
      reportes_title: "Reports",
      reportes_sub: "Sales, dishes, and average ticket",
      tot_sales: "Total sales",
      tot_tip: "Total tips",
      avg_ticket: "Average ticket",
      sessions_closed: "Closed sessions",
      col_date: "Date",
      col_sessions: "Sess.",
      col_sales: "Sales",
      col_tip: "Tips",
      col_total: "Total",
      col_graph: "Graph",
      my_orders: "My orders",
      in_process: "In process",
      ready_pickup: "✓ Ready for pickup!",
      preparing_status: "🔥 Preparing…",
      received_status: "⏱ Received",
      req_bill: "Request bill",
      call_waiter: "Call waiter",
      steak_desc: "Grilled steak with onion and cilantro",
      pastor_desc: "Al pastor pork with pineapple and onion",
      pollo_desc: "Grilled chicken with guacamole",
      agua_desc: "Seasonal, natural",
      refresco_desc: "Cold can",
      churros_desc: "With caramel and cream",
      cart_view: "View order"
    }
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("es");

  // Load language preference from local storage if available
  useEffect(() => {
    const savedLang = localStorage.getItem("kodra_lang");
    if (savedLang === "es" || savedLang === "en") {
      setLanguage(savedLang);
    }
  }, []);

  const toggleLanguage = () => {
    const nextLang = language === "es" ? "en" : "es";
    setLanguage(nextLang);
    localStorage.setItem("kodra_lang", nextLang);
  };

  const t = (section, key) => {
    try {
      return translations[language][section][key] || translations["es"][section][key] || "";
    } catch (e) {
      console.error(`Translation not found: ${section}.${key}`);
      return "";
    }
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
